stages:
    - build
    - deploy

before_script:
    - mix local.hex --force
    - mix local.rebar --force

variables:
    APPLICATION_NAME: astarte_housekeeping_api

mix:test-ci:
    image: elixir:1.5
    services:
        - rabbitmq:3.6
    stage: build
    script:
        - export MIX_ENV=test
        - mix deps.get --force
        - mix deps.compile --force
        - mix compile --force
        - mix coveralls --exclude wip
    cache:
        paths:
            - deps
    except:
        - branches@Astarte-NG/astarte_housekeeping_api

mix:build:
    image: elixir:1.5
    services:
        - rabbitmq:3.6
    stage: build
    script:
        - export MIX_ENV=test
        - mix deps.get --force
        - mix deps.compile --force
        - mix compile --force
        - mix coveralls --exclude wip
        - export MIX_ENV=dev
        - mix release
    cache:
        paths:
            - deps
    only:
        - master@Astarte-NG/astarte_housekeeping_api

mix:release-build:
    image: elixir:1.5
    services:
        - rabbitmq:3.6
    stage: build
    script:
        - export MIX_ENV=prod
        - mix deps.get --force
        - mix deps.compile --force
        - mix compile --force
        - mix test --exclude wip
        - mix release --env=prod
    cache:
        paths:
            - deps
    only:
        - tags@Astarte-NG/astarte_housekeeping_api

docker:snapshot-container:
    image: docker:latest
    before_script:
        - docker info
        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $DOCKER_REGISTRY
    services:
        - docker:stable-dind
    stage: deploy
    only:
        - master@Astarte-NG/astarte_housekeeping_api
    script:
        - docker build -t $DOCKER_REGISTRY/astarte-ng/astarte_housekeeping_api:snapshot .
        - docker push $DOCKER_REGISTRY/astarte-ng/astarte_housekeeping_api:snapshot
